name: ecg
description: "ECG processing pipeline to extract peaks, inter-beat intervals, instantaneous heart rate"

steps:
  - input_data_types: ["ECG"]
    output_data_types: ["ECG_resampled"]
    transforms:
      - transform: Resample
        config:
          new_sample_rate: 128.0
  
  - input_data_types: ["ECG_resampled"]
    output_data_types: ["ECG_filtered", "ECG_peaks"]
    transforms:
      - transform: ECGPeaks
        config:
          peak_detection_method: vg
          correct_artifacts: false
          fix_inversion: true
        
  - input_data_types: ["ECG_peaks"]
    output_data_types: ["ECG_fixed_peaks", "ECG_artifactual_peaks"]
    transforms:
      - transform: FixPeaks
        config:
          aggregate_artifacts: true
        
  - input_data_types: ["ECG_fixed_peaks"]
    output_data_types: ["ECG_ibi", "ECG_hr"]
    transforms:
      - transform: HeartRate
        config:
          interpolation_method: monotone_cubic
