name: eeg_quality
description: "EEG quality scores"

steps:

  - input_data_types: ["EEG_LEFT", "EEG_RIGHT"]
    output_data_types: ["EEG_LEFT_flatness", "EEG_RIGHT_flatness", "EEG_LEFT_amplitude", "EEG_RIGHT_amplitude", "EEG_LEFT_bandpower_score", "EEG_RIGHT_bandpower_score", "EEG_LEFT_bandpower_value", "EEG_RIGHT_bandpower_value", "EEG_LEFT_burstiness", "EEG_RIGHT_burstiness", "EEG_LEFT_kurtosis", "EEG_RIGHT_kurtosis"]
    transforms:
      - transform: EEGQuality
        config:
          segment_duration: 10.0
          flatness_window_duration: 1.0
          std_threshold: 0.5
          max_absolute_value: 200.0
          min_frequency: 0.3
          max_frequency: 20.0
          p2p_threshold: 30.0
          burstiness_window_duration: 0.2