name: ppg
description: "PPG processing pipeline to extract peaks, inter-beat intervals, instantaneous heart rate"

steps:
  - input_data_types: ["PPG"]
    output_data_types: ["PPG_resampled"]
    transforms:
      - transform: Resample
        config:
          new_sample_rate: 128.0

  - input_data_types: ["PPG_resampled"]
    output_data_types: ["PPG_filtered"]
    transforms:
      - transform: FIRFilter
        config:
          low_cutoff: 0.5
          high_cutoff: 8.0
  
  - input_data_types: ["PPG_filtered"]
    output_data_types: ["PPG_peaks"]
    transforms:
      - transform: PPGPeaks
        config:
          peak_detection_method: charlton
          correct_artifacts: false

  - input_data_types: ["PPG_peaks"]
    output_data_types: ["PPG_fixed_peaks", "PPG_artifactual_peaks"]
    transforms:
      - transform: FixPeaks
        config:
          aggregate_artifacts: true

  - input_data_types: ["PPG_fixed_peaks"]
    output_data_types: ["PPG_ibi", "PPG_hr"]
    transforms:
      - transform: HeartRate
        config:
          interpolation_method: monotone_cubic
