name: ppg_processing
description: "PPG processing pipeline to extract peaks, inter-beat intervals, instantaneous heart rate, and signal quality"

steps:
  - input_data_types: ["PPG"]
    output_data_types: ["PPG_resampled"]
    transforms:
      - transform: Resample
        config:
          new_sample_rate: 128.0

  - input_data_types: ["PPG_resampled"]
    output_data_types: ["PPG_filtered"]
    transforms:
      - transform: FIRFilter
        config:
          low_cutoff: 0.5
          high_cutoff: 8.0
  
  - input_data_types: ["PPG_filtered"]
    output_data_types: ["PPG_peaks", "PPG_ibi", "PPG_rate"]
    transforms:
      - transform: PPGProcess
        config:
          peak_detection_method: elgendi
          correct_artifacts: true

  # Quality assessment (optional, computationally expensive)
  # - input_data_types: ["PPG_filtered", "PPG_peaks"]
  #   output_data_types: ["PPG_quality"]
  #   transforms:
  #     - transform: PPGQuality
  #       config:
  #         quality_method: templatematch
