name: ppg_artifact
description: "PPG artifact detection based on IBI and signal quality metrics"

steps:

  - input_data_types: ["PPG_filtered", "PPG_peaks", "PPG_ibi", "PPG_rate"]
    output_data_types: ["PPG_filtered", "PPG_peaks", "PPG_ibi", "PPG_rate"]
    transforms:
      - transform: TrimToMultiple
        config:
          duration: 10.0

  - input_data_types: ["PPG_filtered", "PPG_peaks"]
    output_data_types: ["PPG_quality"]
    transforms:
      - transform: PPGQuality
        config:
          quality_method: templatematch

  - input_data_types: ["PPG_ibi", "PPG_quality"]
    output_data_types: ["PPG_artifact"]
    transforms:
      - transform: PPGArtifactLabels
        config:
          segment_duration: 10
          quality_threshold: 0.8
          ibi_range: [300, 2000]  # Valid IBI range in ms
          min_valid_ratio: 0.5  # Minimum ratio of valid samples in segment

  # - input_data_types: ["annotations", "PPG_artifact"]
  #   output_data_types: ["annotations"]
  #   transforms:
  #     - transform: MergeArtifactLabels
