name: zmax_datasets
description: "Convert ZMax EEG data from V to uV"

steps:

  - input_data_types: ["EEG_LEFT", "EEG_RIGHT"]
    output_data_types: ["EEG_LEFT", "EEG_RIGHT"]
    transforms:
      - transform: Multiply
        config:
          factor: 1000000 # V to uV