name: zmax_datasets
description: "Extract and rename data types from wearanize+ dataset"

steps:

  - input_data_types: ["EEG_LEFT", "EEG_RIGHT"]
    output_data_types: ["EEG_LEFT", "EEG_RIGHT"]
    transforms:
      - transform: Scale
        config:
          scale_factor: 1000000
          