[tool.poetry]
name = "zmax-real-time"
version = "0.1.0"
description = ""
authors = ["Ali Saberi <ali.saberi96@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
torch = "^2.4.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.5"
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
