datasets:
  donders_2022:
    data_dir: /project/3013097.06/Data
    channel_names: [EEG L, EEG R]
    annotations: [sleep_stage]
    selected_subjects: [33]
    selected_sessions: [15]
    # excluded_subjects: []
    # excluded_sessions: []
    # excluded_sessions_for_subjects:
    #   1: [1, 8]