- name: donders_2022
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/ppg_processed/donders_2022
    
- name: qs
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/ppg_processed/qs
    
- name: donders_2018
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/ppg_processed/donders_2018

- name: karolinska
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/ppg_processed/karolinska

- name: wearanize_plus
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/ppg_processed/wearanize_plus

- name: abc
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/abc

- name: ccshs
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/ccshs

- name: cfs
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/cfs

- name: chat
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/chat

- name: dcsm
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/dcsm

- name: homepap
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/homepap

- name: mesa
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/mesa

- name: mros
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/mros

- name: phys
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/phys

- name: shhs
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/shhs

- name: sof
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/sleep_datasets/processed/sof
