- name: donders_2022
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/raw/donders_2022
    
- name: qs
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/raw/qs
    
- name: donders_2018
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/raw/donders_2018

- name: karolinska
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/raw/karolinska

- name: wearanize_plus
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.48/sleep_staging/zmax_datasets/raw/wearanize_plus

- name: abc
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/abc

- name: ccshs
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/ccshs

- name: cfs
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/cfs

- name: chat
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/chat

- name: dcsm
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/dcsm

- name: homepap
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/homepap

- name: mesa
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/mesa

- name: mros
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/mros

- name: phys
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/phys

- name: shhs
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/shhs

- name: sof
  dataset_type: USleepDataset
  config:
    data_dir: /project/4180000.46/sleep_datasets/raw/sof
